puts 'seeding english'

English.create(name: "Ibrahim the librarian", age: "29", date: "25 November 2018", location: "Karaj, Alborz", cause: "A bullet hit the heart",image_small: "https://sanelrsiranshutprod001.blob.core.windows.net/assets/iran_victim/medium_48px/V062_48px.jpg", image_large: "https://sanelrsiranshutprod001.blob.core.windows.net/assets/iran_victim/large_350px/V062_large.jpg")
English.create(name: "Ibrahim Moradi", age: "21", date: "25 November 2018", location: "Javanrud, Kermanshah", cause: "Shot in the head",image_small: "https://sanelrsiranshutprod001.blob.core.windows.net/assets/iran_victim/medium_48px/V065_48px.jpg", image_large: "https://sanelrsiranshutprod001.blob.core.windows.net/assets/iran_victim/large_350px/V065_large.jpg")
English.create(name: "Ebrahim Motauri", age: "Unknown", date: "25 November 2018", location: "Abadan, Khuzestan", cause: "Shots in the back and chest",image_small: "https://sanelrsiranshutprod001.blob.core.windows.net/assets/iran_victim/medium_48px/V061_48px.jpg", image_large: "https://sanelrsiranshutprod001.blob.core.windows.net/assets/iran_victim/large_350px/V061_large.jpg")
English.create(name: "Ibrahim Mansouri", age: "Unknown", date: "26 November 2018", location: "Yazdanshahr, Isfahan", cause: "shot",image_small: "https://sanelrsiranshutprod001.blob.core.windows.net/assets/iran_victim/medium_48px/V063_48px.jpg", image_large: "https://sanelrsiranshutprod001.blob.core.windows.net/assets/iran_victim/large_350px/V063_large.jpg")
English.create(name: "Ibrahim Mehdipour", age: "50", date: "25 November 2018", location: "Andisheh, Tehran", cause: "shot",image_small: "https://sanelrsiranshutprod001.blob.core.windows.net/assets/iran_victim/medium_48px/V064_48px.jpg", image_large: "https://sanelrsiranshutprod001.blob.core.windows.net/assets/iran_victim/large_350px/V064_large.jpg")
puts 'done seeding english'

puts 'seeding farsi'
Farsi.create(name: "ابراهیم کتابدار", age: '29', date: "۲۵ آبان ۹۸", location: "کرج، البرز", cause: "اصابت گلوله به قلب",image_small: "https://sanelrsiranshutprod001.blob.core.windows.net/assets/iran_victim/medium_48px/V062_48px.jpg", image_large: "https://sanelrsiranshutprod001.blob.core.windows.net/assets/iran_victim/large_350px/V062_large.jpg")
Farsi.create(name: "ابراهیم مرادی", age: '21', date: "۲۵ آبان ۹۸", location: "جوانرود، کرمانشاه", cause: "اصابت گلوله به سر",image_small: "https://sanelrsiranshutprod001.blob.core.windows.net/assets/iran_victim/medium_48px/V065_48px.jpg", image_large: "https://sanelrsiranshutprod001.blob.core.windows.net/assets/iran_victim/large_350px/V065_large.jpg")
Farsi.create(name: "ابراهیم مطوری", age: 'نامشخص', date: "۲۵ آبان ۹۸", location: "آبادان، خوزستان", cause: "اصابت گلوله به پشت و سینه",image_small: "https://sanelrsiranshutprod001.blob.core.windows.net/assets/iran_victim/medium_48px/V061_48px.jpg", image_large: "https://sanelrsiranshutprod001.blob.core.windows.net/assets/iran_victim/large_350px/V061_large.jpg")
puts 'done seeding farsi'
